#### import the given csv file `(pokedex.csv)` as a DataFrame and do the following operations:

In [6]:
import pandas as pd
df = pd.read_csv("pokedex.csv")

1. Remove the last two columns [`Abil1`, `Abil2`]

In [7]:
df.drop(columns=["Abil1", "Abil2"], inplace=True)
df.head()

   DexNum        Name  HP  PA  PD   SA   SD  SP  BST  Type1   Type2
0       1   BULBASAUR  45  49  49   65   65  45  318  GRASS     ...
1       2     IVYSAUR  60  62  63   80   80  60  405  GRASS  POISON
2       3    VENUSAUR  80  82  83  100  100  80  525  GRASS  POISON
3       4  CHARMANDER  39  52  43   60   50  65  309   FIRE     ...
4       5  CHARMELEON  58  64  58   80   65  80  405   FIRE     ...

2. Wherever the entry for `Type2` column in `"..."`, set it to the same value as that of `Type1` in that row

Example:
```
001,"BULBASAUR",45,49,49,65,65,45,318,GRASS,...
```
should become
```
001,"BULBASAUR",45,49,49,65,65,45,318,GRASS,GRASS
```

In [8]:
df["Type2"] = df.apply(
    lambda row: row["Type1"] if row["Type2"] == "..." else row["Type2"], axis=1
)
df.head()

   DexNum        Name  HP  PA  PD   SA   SD  SP  BST  Type1   Type2
0       1   BULBASAUR  45  49  49   65   65  45  318  GRASS   GRASS
1       2     IVYSAUR  60  62  63   80   80  60  405  GRASS  POISON
2       3    VENUSAUR  80  82  83  100  100  80  525  GRASS  POISON
3       4  CHARMANDER  39  52  43   60   50  65  309   FIRE    FIRE
4       5  CHARMELEON  58  64  58   80   65  80  405   FIRE    FIRE

3. Rename the following columns:
- PA as ph_Atk
- PD as ph_Def
- SA as sp_Atk
- SD as sp_Def
- SP as speed
- BST as total_Stats

In [10]:
df.rename(
    columns={
        "PA": "ph_Atk",
        "PD": "ph_Def",
        "SA": "sp_Atk",
        "SD": "sp_Def",
        "SP": "speed",
        "BST": "total_Stats",
    },
    inplace=True,
)
df.head()

,DexNum,Name,HP,ph_Atk,ph_Def,sp_Atk,sp_Def,speed,total_Stats,Type1,Type2
0,1,BULBASAUR,45,49,49,65,65,45,318,GRASS,GRASS
1,2,IVYSAUR,60,62,63,80,80,60,405,GRASS,POISON
2,3,VENUSAUR,80,82,83,100,100,80,525,GRASS,POISON
3,4,CHARMANDER,39,52,43,60,50,65,309,FIRE,FIRE
4,5,CHARMELEON,58,64,58,80,65,80,405,FIRE,FIRE

4. Show the top pokemon in each stat (HP, pA, pD, sA, sD, sp). Store them in a single dataFrame in the following format:

```code
stat    topPokemon
HP      name1
PA      name2
...
SP      name6
```

In [13]:

stats = ["HP", "ph_Atk", "ph_Def", "sp_Atk", "sp_Def", "speed"]
top_pokemon = {"stat": [], "topPokemon": []}

for stat in stats:
    top_row = df.loc[df[stat].idxmax()]
    top_pokemon["stat"].append(stat)
    top_pokemon["topPokemon"].append(top_row["Name"])

top_df = pd.DataFrame(top_pokemon)
top_df.head()

     stat topPokemon
0      HP    BLISSEY
1  ph_Atk    SLAKING
2  ph_Def    KLEAVOR
3  sp_Atk     MEWTWO
4  sp_Def    KLEAVOR